FROM ubuntu:14.04

RUN apt-get update \
 && apt-get install -y \
        build-essential \
        cmake \
        gdb \
        libboost-all-dev \
        libmarble-dev \
        libqt4-dev \
        libqt4-dev-bin \
        libusb-1.0-0-dev \
        libusb-dev \
        pkg-config \
        qt4-qmake \
 && apt-get clean
